'''
Define constants
'''

HEADER_OK = 'OK'
HEADER_CLIENT_HELLO = 'CLIENT HELLO'

HEADER_NODE_ACTIVE = 'NODE ACTIVE'
HEADER_NODE_TERMINATED = 'NODE TERMINATED'

HEADER_CLIENT_GET = 'CLIENT GET'
HEADER_CLIENT_PUT = 'CLIENT PUT'

M = 10
K = 3
